### ISSUE TITLE
v1.1.0 doesn't work with Qt Creator 4.6

### ISSUE THREAD

**Issue by moberhuber** [CJCombrink/SpellChecker-Plugin#84]
Qt Creator 4.6 was just released https://www1.qt.io/offline-installers/#section-13

Unfortunately, the SpellChecker-Plugin fails to load with Qt Creator 4.6 on Ubuntu 14. I suppose that a rebuild against latest QtC would be necessary. It would be great if a new release could be posted.

**Comment by CJCombrink** [comment]
Unfortunately I have just left for holiday, I will release as soon as i get back in about 2 weeks.

**Comment by moberhuber** [comment]
It looks like a bit more than just a recompile is needed this time, because Project::files() now returns a FileNameList instead for a QStringList: https://codereview.qt-project.org/#/c/213596/

**Comment by becrux** [comment]
Well, that's the easy part. The point is that there's also a crash:

No symbol table info available.
#6  0x00007fd4a275d089 in qt_assert_x(char const*, char const*, char const*, int) () from /home/d068830/qt/qt5100/lib/libQt5Core.so.5

No symbol table info available.
#7  0x00007fd4862d95eb in SpellChecker::Internal::SpellCheckerCoreOptionsWidget::updateWithSettings (this=0x3c088e0, settings=0x1f099b0) at spellcheckercoreoptionswidget.cpp:109

        index = -1
        __PRETTY_FUNCTION__ = "void SpellChecker::Internal::SpellCheckerCoreOptionsWidget::updateWithSettings(const SpellChecker::Internal::SpellCheckerCoreSettings*)"

#8  0x00007fd4862d90ad in SpellChecker::Internal::SpellCheckerCoreOptionsWidget::SpellCheckerCoreOptionsWidget (this=0x3c088e0, settings=0x1f099b0, parent=0x0) at spellcheckercoreoptionswidget.cpp:67

        availableSpellCheckers = {d = 0x1f1dc50}
        index = 0

        currentSpellChecker = 0x1f1bf10

#9  0x00007fd4862d7512 in SpellChecker::Internal::SpellCheckerCoreOptionsPage::widget (this=0x1f18700) at spellcheckercoreoptionspage.cpp:54

Having a look.
