### ISSUE TITLE
Plugin crashes randomly

### ISSUE THREAD

**Issue by maciekgajewski** [CJCombrink/SpellChecker-Plugin#96]
Version 1.3, QtCreator 4.7

Backtrace:

```
#0  0x00007f19bd73de97 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f19bd73f801 in __GI_abort () at abort.c:79
#2  0x00007f19bd788897 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7f19bd8b5b9a "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007f19bd78f90a in malloc_printerr (str=str@entry=0x7f19bd8b7828 "double free or corruption (fasttop)") at malloc.c:5350
#4  0x00007f19bd797004 in _int_free (have_lock=0, p=0x7f195a45cac0, av=0x7f1958000020) at malloc.c:4230
#5  0x00007f19bd797004 in __GI___libc_free (mem=0x7f195a45cad0) at malloc.c:3124
#6  0x00007f19be9d6314 in QHashData::free_helper(void (*)(QHashData::Node*)) () at /home/maciek/software/qtcreator-4.7.1/bin/../lib/Qt/lib/libQt5Core.so.5
#7  0x00007f1987c9076c in SpellChecker::CppSpellChecker::Internal::CppDocumentParser::parseCppDocument(QSharedPointer<CPlusPlus::Document>) ()
    at /home/maciek/software/qtcreator-4.7.1/lib/qtcreator/plugins/libSpellChecker.so
#8  0x00007f1987c915b3 in SpellChecker::CppSpellChecker::Internal::CppDocumentParser::parseCppDocumentOnUpdate(QSharedPointer<CPlusPlus::Document>) ()
    at /home/maciek/software/qtcreator-4.7.1/lib/qtcreator/plugins/libSpellChecker.so
#9  0x00007f1987c91c36 in QtPrivate::QSlotObject<void (SpellChecker::CppSpellChecker::Internal::CppDocumentParser::*)(QSharedPointer<CPlusPlus::Document>), QtPrivate::List<QSharedPointer<CPlusPlus::Document> >, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) ()
    at /home/maciek/software/qtcreator-4.7.1/lib/qtcreator/plugins/libSpellChecker.so
#10 0x00007f19beb6b4b6 in QMetaObject::activate(QObject*, int, int, void**) () at /home/maciek/software/qtcreator-4.7.1/bin/../lib/Qt/lib/libQt5Core.so.5
#11 0x00007f1996b602b5 in CppTools::CppModelManager::documentUpdated(QSharedPointer<CPlusPlus::Document>) ()
    at /home/maciek/software/qtcreator-4.7.1/lib/qtcreator/plugins/libCppTools.so
#12 0x00007f1996af4808 in CppTools::CppModelManager::emitDocumentUpdated(QSharedPointer<CPlusPlus::Document>) ()
    at /home/maciek/software/qtcreator-4.7.1/lib/qtcreator/plugins/libCppTools.so
#13 0x00007f1996af48b9 in std::_Function_handler<void (QSharedPointer<CPlusPlus::Document> const&), CppTools::CppModelManager::createSourceProcessor()::{lambda(QSharedPointer<CPlusPlus::Document> const&)#1}>::_M_invoke(std::_Any_data const&, QSharedPointer<CPlusPlus::Document> const&) ()
    at /home/maciek/software/qtcreator-4.7.1/lib/qtcreator/plugins/libCppTools.so
#14 0x00007f1996b1ad98 in CppTools::Internal::CppSourceProcessor::sourceNeeded(unsigned int, QString const&, CPlusPlus::Client::IncludeType, QStringList const&) ()
    at /home/maciek/software/qtcreator-4.7.1/lib/qtcreator/plugins/libCppTools.so
#15 0x00007f1996734d4f in CPlusPlus::Preprocessor::handleIncludeDirective(CPlusPlus::Internal::PPToken*, bool) ()
    at /home/maciek/software/qtcreator-4.7.1/lib/qtcreator/plugins/../libCPlusPlus.so.4
#16 0x00007f1996736200 in CPlusPlus::Preprocessor::handlePreprocessorDirective(CPlusPlus::Internal::PPToken*) ()
    at /home/maciek/software/qtcreator-4.7.1/lib/qtcreator/plugins/../libCPlusPlus.so.4
#17 0x00007f199673226b in CPlusPlus::Preprocessor::lex(CPlusPlus::Internal::PPToken*) () at /home/maciek/software/qtcreator-4.7.1/lib/qtcreator/plugins/../libCPlusPlus.so.4
#18 0x00007f1996732deb in CPlusPlus::Preprocessor::preprocess(QString const&, QByteArray const&, QByteArray*, QByteArray*, bool, bool, bool, unsigned int, unsigned int, unsigned int) () at /home/maciek/software/qtcreator-4.7.1/lib/qtcreator/plugins/../libCPlusPlus.so.4
#19 0x00007f1996733580 in CPlusPlus::Preprocessor::run(QString const&, QByteArray const&, bool, bool) ()
    at /home/maciek/software/qtcreator-4.7.1/lib/qtcreator/plugins/../libCPlusPlus.so.4
#20 0x00007f1996b1aac7 in CppTools::Internal::CppSourceProcessor::sourceNeeded(unsigned int, QString const&, CPlusPlus::Client::IncludeType, QStringList const&) ()
    at /home/maciek/software/qtcreator-4.7.1/lib/qtcreator/plugins/libCppTools.so
#21 0x00007f1996a68d28 in (anonymous namespace)::parse(QFutureInterface<void>&, QFutureInterface<void> const&, (anonymous namespace)::ParseParams) ()
    at /home/maciek/software/qtcreator-4.7.1/lib/qtcreator/plugins/libCppTools.so
#22 0x00007f1996a62f0c in Utils::Internal::AsyncJob<void, void (&)(QFutureInterface<void>&, QFutureInterface<void> const&, (anonymous namespace)::ParseParams), QFutureInterface<void> const&, (anonymous namespace)::ParseParams&>::run() () at /home/maciek/software/qtcreator-4.7.1/lib/qtcreator/plugins/libCppTools.so
#23 0x00007f19be97ee3f in QThreadPoolThread::run() () at /home/maciek/software/qtcreator-4.7.1/bin/../lib/Qt/lib/libQt5Core.so.5
#24 0x00007f19be988564 in QThreadPrivate::start(void*) () at /home/maciek/software/qtcreator-4.7.1/bin/../lib/Qt/lib/libQt5Core.so.5
#25 0x00007f19be4366db in start_thread (arg=0x7f19437fe700) at pthread_create.c:463
#26 0x00007f19bd82088f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by maciekgajewski** [comment]
Linux, Ubuntu 18.04.1. 64-bit.
Hunspell 3.2.06, using /usr/share/hunspell/en_GB.dic as my dict.My user dict is empty.
I use the default settings on the plugin.

**Comment by CJCombrink** [comment]
@maciekgajewski Can you please test the latest release (v2.0.0) to see if this is still an issue.

I have fixed a few crash issues, one specifically around the QHash.

I am closing the issue for now, please comment if I should re-open.
